[package]
name = "bc-receipt-splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3.0-alpha.2"
itertools = "0.10.3"
rust_decimal = "1.22"
rust_decimal_macros = "1.22"
